IF  EXISTS (SELECT * FROM sys.databases WHERE name = N'QLHocSinh')
    BEGIN
		USE master
        DROP DATABASE QLHocSinh
    END;
CREATE DATABASE QLHocSinh
USE QLHocSinh
GO

CREATE TABLE Lop
(
	MaLop INT IDENTITY(1,1)  PRIMARY KEY,
	TenLop NVARCHAR(50)
)
GO
CREATE TABLE MonHoc
(
  MaMH INT IDENTITY(1,1) PRIMARY KEY,
  TenMH NVARCHAR(50),
)
GO
CREATE TABLE LoaiDiem
(
 MaLoai INT IDENTITY(1,1) PRIMARY KEY,
 TenLoai NVARCHAR(50),
 HeSo INT
)
GO
CREATE TABLE HocSinh (
	IDHS INT IDENTITY(1,1) NOT NULL PRIMARY KEY CLUSTERED,
	MaHS AS 'HS'+RIGHT('00000000' +CAST(IDHS AS VARCHAR(8)),8) PERSISTED,
	Ho NVARCHAR(50),
	Ten NVARCHAR(50),
	GioiTinh BIT,
	NgaySinh DATE,
	DiaChi NVARCHAR(100),
	Email VARCHAR(50),
	Sdt VARCHAR(15),
)
GO
CREATE TABLE HocSinhThuocLop(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	IDHS int FOREIGN KEY (IDHS) REFERENCES HocSinh(IDHS),
	MaLop INT FOREIGN KEY(MaLop) REFERENCES Lop(MaLop)
)
GO
CREATE TABLE GiaoVien (
	IDGV INT IDENTITY(1,1) NOT NULL PRIMARY KEY CLUSTERED,
	MaGV AS 'GV'+RIGHT('00000000' +CAST(IDGV AS VARCHAR(8)),8) PERSISTED,
	Ho NVARCHAR(50),
	Ten NVARCHAR(50),
	GioiTinh BIT,
	NgaySinh DATE,
	DiaChi NVARCHAR(100),
	Email VARCHAR(50),
	Sdt VARCHAR(15),
	MaMH INT FOREIGN KEY (MaMH) REFERENCES MonHoc(MaMH)
) 
GO 
CREATE TABLE PhanCong(
ID INT IDENTITY(1,1) PRIMARY KEY,
IDGV INT FOREIGN KEY(IDGV) REFERENCES GiaoVien(IDGV),
MaLop INT FOREIGN KEY(MaLop) REFERENCES Lop(MaLop)
)
GO
CREATE TABLE LoaiTaiKhoan(
MaLoai int identity(1,1) primary key,
TenLoai nvarchar(50)
)

GO
CREATE TABLE TaiKhoan(
TaiKhoan VARCHAR(20) PRIMARY KEY,
MatKhau VARCHAR(20),
IDGV INT FOREIGN KEY(IDGV) REFERENCES GiaoVien(IDGV),
MaLoai INT FOREIGN KEY (MaLoai) REFERENCES LoaiTaiKhoan(MaLoai),
)
GO
CREATE TABLE BangDiem
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	IDHS INT FOREIGN KEY(IDHS) REFERENCES HocSinh(IDHS),
	MaMH INT FOREIGN KEY (MaMH) REFERENCES MonHoc(MaMH),
	Diem15 float,
	Diem1Tiet float,
	DiemTB float,
	HocKi int,
	
)


CREATE TABLE QuiDinh
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	TuoiMin INT,
	TuoiMax INT,
	SiSoMax INT,
	DiemDat INT
)