//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel;
namespace WebQLHS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangDiem
    {
        [DisplayName("ID")]
        public int ID { get; set; }
        [DisplayName("IDHS")]
        public Nullable<int> IDHS { get; set; }
        [DisplayName("Mã môn học")]
        public Nullable<int> MaMH { get; set; }
        [DisplayName("Điểm 15 phút")]
        public Nullable<double> Diem15 { get; set; }
        [DisplayName("Điểm 1 Tiết")]
        public Nullable<double> Diem1Tiet { get; set; }
        [DisplayName("Điểm trung bình")]
        public Nullable<double> DiemTB { get; set; }
        [DisplayName("Học Kì")]
        public Nullable<int> HocKi { get; set; }
        public virtual HocSinh HocSinh { get; set; }
        public virtual MonHoc MonHoc { get; set; }
    }
}
