//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLHS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class QuiDinh
    {
        public int ID { get; set; }
        [DisplayName("Tuổi tối thiểu")]
        public Nullable<int> TuoiMin { get; set; }
        [DisplayName("Tuổi tối đã")]
        public Nullable<int> TuoiMax { get; set; }
        [DisplayName("Sĩ số tối đã")]
        public Nullable<int> SiSoMax { get; set; }
        [DisplayName("Điểm đạt")]
        public Nullable<int> DiemDat { get; set; }
    }
}
