//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLHS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
        
    public partial class TaiKhoan
    {   
        [DisplayName("Tài Khoản")]
        public string TaiKhoan1 { get; set; }
        [DisplayName("Mật khẩu")]
        public string MatKhau { get; set; }
        [DisplayName("ID Giáo Viên")]
        public Nullable<int> IDGV { get; set; }
        [DisplayName("Mã Loại")]
        public Nullable<int> MaLoai { get; set; }
        public virtual GiaoVien GiaoVien { get; set; }
        [DisplayName("Loại tài khoản")]
        public virtual LoaiTaiKhoan LoaiTaiKhoan { get; set; }
    }
}
